---
- hosts: webservers

  # an encrypted ansible secret file containing the sudo password
  vars_files:
    - secret

  roles:
    - portfolio

  environment:
    DEBUG: "{{ lookup('ansible.builtin.env', 'DEBUG') }}"
        # Added new variables
    PORTFOLIO_DOMAIN: "{{ lookup('ansible.builtin.env', 'PORTFOLIO_DOMAIN') }}"
    PORTAINER_DOMAIN: "{{ lookup('ansible.builtin.env', 'PORTAINER_DOMAIN') }}"
